rules:
  - matches:
      datasources:
        - browser-version
      dependencyNames:
        - chrome
        - chrome-for-testing
    dependencyConfig:
      versioning: "^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$"
      maxUpdateType: major
  - matches:
      datasources:
        - browser-version
      dependencyNames:
        - firefox
    dependencyConfig:
      versioning: "^(\\d+)\\.(\\d+)(?:\\.(\\d+))?(?:\\.(\\d+))?(?:([a-z]+)(\\d+))?$"
      maxUpdateType: major
