# Rules for dockerfile manager and versioning from docker datasource
rules:
  # The dockerfile manager
  - matches:
      managerTypes:
        - dockerfile
    managerConfig:
      filePatterns:
        - "**/Dockerfile"
  # Docker images versioning
  - matches:
      dependencyNames:
        - alpine
    dependencyConfig:
      versioning: preset:semver
