# Rules for docker related managers and versioning from docker datasource
rules:
  # The dockerfile manager
  - matches:
      managerTypes:
        - dockerfile
    managerConfig:
      filePatterns:
        - "**/Dockerfile"

  # The docker-compose manager
  - matches:
      managerTypes:
      - docker-compose
    managerConfig:
      filePatterns:
        - "**/docker-compose.yml"

  # Docker images versioning
  - matches:
      dependencyNames:
        - alpine
    dependencyConfig:
      versioning: preset:semver
