# gonovate: { "datasource":"docker", "matchstring":"(?m)^FROM (?P<packageName>.*):(?P<version>.*)$", "versioning":"^(\\d+)\\.(\\d+)\\.(\\d+)-bookworm$" }
FROM mcr.microsoft.com/devcontainers/base:1.0.11-bookworm
