# gonovate: { "datasource":"docker", "matchString":"(?m)^FROM (?P<dependencyName>.+):(?P<version>[^\\s]+)\\s*$", "versioning":"^(\\d+)\\.(\\d+)\\.(\\d+)-bookworm$" }
FROM mcr.microsoft.com/devcontainers/base:1.0.0-bookworm
