name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      make_release:
        description: 'True to make a release'
        required: true
        type: boolean

env:
  # gonovate: { "datasource":"go-version", "dependencyName":"go-stable", "matchString":"preset:key-value(GO_VERSION)" }
  GO_VERSION: 1.23.0

jobs:
  # Build Job
  build:
    runs-on: ubuntu-24.04
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        run: |
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          wget --no-verbose "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
          rm "go${GO_VERSION}.linux-amd64.tar.gz"

      - name: Build
        run: go run ./build/build.go --target "Compile:All"

      - name: Test
        run: go run ./build/build.go --target "Test"

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-report
          path: .test-reports/junit-test-report.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: .test-reports/junit-test-report.xml
          reporter: java-junit

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-windows
          path: .build-output/*windows*.zip

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-linux
          path: .build-output/*linux*.zip

      - name: Upload Darwin Intel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-darwin-intel
          path: .build-output/*darwin*amd*.zip

      - name: Upload Darwin ARM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-darwin-arm
          path: .build-output/*darwin*arm*.zip

  # Release Job
  release:
    if: ${{ inputs.make_release }}
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: .build-output/
          pattern: binary-*
          merge-multiple: true

      - name: Install Go
        run: |
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          wget --no-verbose "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
          rm "go${GO_VERSION}.linux-amd64.tar.gz"

      - name: Create the release
        run:  go run ./build/build.go --target "Release"
