name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      make_release:
        description: 'True to make a release'
        required: true
        type: boolean

env:
  GO_VERSION: 1.22.1

jobs:
  # Build Job
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        run: |
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          wget --no-verbose "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
          rm "go${GO_VERSION}.linux-amd64.tar.gz"

      - name: Build
        run:  go run ./build/build.go --target "Compile:All"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: .build-output/

  # Release Job
  release:
    if: ${{ inputs.make_release }}
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: .build-output/

      - name: Install Go
        run: |
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          wget --no-verbose "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
          rm "go${GO_VERSION}.linux-amd64.tar.gz"

      - name: Create the release
        run:  go run ./build/build.go --target "Release:Create"
